[2020-04-08 15:10:23.204] [main] [ERROR] com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
[2020-04-08 15:14:22.204] [job -run] [ERROR] com.piesat.schedule.rpc.lock.RedisLock - org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:68)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:253)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy274.get(Unknown Source)
	at com.piesat.schedule.rpc.lock.RedisLock.lambda$lock$0(RedisLock.java:42)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at com.piesat.schedule.rpc.lock.RedisLock.lock(RedisLock.java:32)
	at com.piesat.schedule.rpc.lock.RedisLock.tryLock(RedisLock.java:64)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrrigerWhile(ScheduleThread.java:93)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrriger(ScheduleThread.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy252.get(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:66)
	... 15 more

[2020-04-08 15:17:51.331] [job -run] [ERROR] com.piesat.schedule.rpc.lock.RedisLock - org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setNX(LettuceStringCommands.java:205)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.setNX(DefaultedRedisConnection.java:288)
	at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy274.setNX(Unknown Source)
	at com.piesat.schedule.rpc.lock.RedisLock.lambda$lock$0(RedisLock.java:35)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at com.piesat.schedule.rpc.lock.RedisLock.lock(RedisLock.java:32)
	at com.piesat.schedule.rpc.lock.RedisLock.tryLock(RedisLock.java:64)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrrigerWhile(ScheduleThread.java:93)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrriger(ScheduleThread.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy252.setnx(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setNX(LettuceStringCommands.java:203)
	... 15 more

[2020-04-08 15:18:24.716] [job -run] [ERROR] com.piesat.schedule.rpc.lock.RedisLock - org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:68)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:253)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy274.get(Unknown Source)
	at com.piesat.schedule.rpc.lock.RedisLock.lambda$lock$0(RedisLock.java:42)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at com.piesat.schedule.rpc.lock.RedisLock.lock(RedisLock.java:32)
	at com.piesat.schedule.rpc.lock.RedisLock.tryLock(RedisLock.java:64)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrrigerWhile(ScheduleThread.java:93)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrriger(ScheduleThread.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy252.get(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:66)
	... 15 more

[2020-04-08 15:18:47.746] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 15:18:48.381] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 15:18:48.381] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 15:18:48.472] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:08:15.647] [main] [ERROR] com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
[2020-04-08 17:09:57.683] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:09:58.769] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:00.141] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:02.783] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:03.316] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:07.679] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:14.467] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:26.893] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:33.332] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:10:46.214] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:11:03.346] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:11:17.300] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:11:33.364] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:12:03.113] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:12:21.280] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:12:31.641] [job -run] [ERROR] com.piesat.schedule.rpc.lock.RedisLock - org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setNX(LettuceStringCommands.java:205)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.setNX(DefaultedRedisConnection.java:288)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy271.setNX(Unknown Source)
	at com.piesat.schedule.rpc.lock.RedisLock.lambda$lock$0(RedisLock.java:35)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at com.piesat.schedule.rpc.lock.RedisLock.lock(RedisLock.java:32)
	at com.piesat.schedule.rpc.lock.RedisLock.tryLock(RedisLock.java:64)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrrigerWhile(ScheduleThread.java:93)
	at com.piesat.schedule.rpc.thread.ScheduleThread.jobToTrriger(ScheduleThread.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy252.setnx(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setNX(LettuceStringCommands.java:203)
	... 15 more

[2020-04-08 17:12:51.289] [grpc-default-executor-0] [ERROR] n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for 10.1.6.115:6007
[2020-04-08 17:14:45.353] [main] [ERROR] com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
[2020-04-08 17:15:42.117] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:15:42.975] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:15:42.976] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:15:43.049] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:16:23.287] [insert-oper-log-1] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:16:23.580] [insert-oper-log-1] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:16:23.581] [insert-oper-log-1] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:16:23.591] [insert-oper-log-1] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:18:58.763] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:18:59.117] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:18:59.117] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:18:59.196] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:23:31.257] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:23:31.717] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:23:31.717] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:23:31.764] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:25:45.119] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:25:45.754] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:25:45.754] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:25:45.831] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:30:34.765] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:30:35.139] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:30:35.139] [insert-oper-log-0] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:30:35.179] [insert-oper-log-0] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:30:45.395] [insert-oper-log-1] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:30:45.537] [insert-oper-log-1] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:30:45.537] [insert-oper-log-1] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:30:45.553] [insert-oper-log-1] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:30:51.498] [insert-oper-log-2] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:30:51.675] [insert-oper-log-2] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:30:51.675] [insert-oper-log-2] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:30:51.687] [insert-oper-log-2] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:30:57.643] [insert-oper-log-3] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:30:57.776] [insert-oper-log-3] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:30:57.776] [insert-oper-log-3] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:30:57.791] [insert-oper-log-3] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:31:03.785] [insert-oper-log-4] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:31:03.968] [insert-oper-log-4] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:31:03.968] [insert-oper-log-4] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:31:03.976] [insert-oper-log-4] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:31:09.979] [insert-oper-log-5] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-08 17:31:10.116] [insert-oper-log-5] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 执行表备份失败,资料名称缓冲库_基础库_全球高空定时值数据（原始表）
[2020-04-08 17:31:10.116] [insert-oper-log-5] [ERROR] c.p.schedule.client.handler.backup.BackupHandler - 备份任务ID361b99a9a04f4d46b9794edff657845b,任务名缓冲库_基础库_全球高空定时值数据（原始表）,错误ReturnT [code=1, msg=备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null]
[2020-04-08 17:31:10.126] [insert-oper-log-5] [ERROR] com.piesat.schedule.client.util.EiSendUtil - eivalues执行虚谷备份异常
[2020-04-08 17:31:16.087] [insert-oper-log-6] [ERROR] com.piesat.schedule.client.business.XuguBusiness - 备份K表USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB失败,sqlselect * from USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB where D_DATA_ID='B.0011.0001.S001' and D_DATETIME<'2020-04-07 00:00:00' and D_DATETIME>='2020-04-06 00:00:00',错误java.io.FileNotFoundException: /space/app/sod/backup/testTempPath/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004/BFDB--USR_SOD.UPAR_WEA_GLB_MUL_FTM_K_ORI_TAB--20200406--B.0011.0001.M004.exp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.piesat.schedule.client.util.Select2File.expparttab2(Select2File.java:37)
	at com.piesat.schedule.client.business.XuguBusiness.backUpKtable(XuguBusiness.java:54)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backUpTable(BackupHandler.java:311)
	at com.piesat.schedule.client.handler.backup.BackupHandler.backupExecute(BackupHandler.java:249)
	at com.piesat.schedule.client.handler.backup.BackupHandler.preParam(BackupHandler.java:145)
	at com.piesat.schedule.client.handler.backup.BackupHandler.execute(BackupHandler.java:74)
	at com.piesat.schedule.client.service.ExecutorBizServiceImpl.lambda$execute$0(ExecutorBizServiceImpl.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

